---
title: "Pull Weather Data"
author: "Rissler"
date: "10/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(darksky)
library(lubridate)
library(ggformula)
```

## Problem

Need historical weather data for Loras from Launch to official count day for 2016-2019.

##  The dates

2019 08/21 - 09/13 (https://myweb.loras.edu/Loras/PDF/AcademicCalendar2019-20.pdf)
2018 08/22 - 09/14 (https://myweb.loras.edu/Loras/PDF/AcademicCalendar2018-2019.pdf)
2017 08/23 - 09/15 (https://myweb.loras.edu/Loras/PDF/AcademicCalendar2017-2018.pdf)
2016 08/24 - 09/16 (https://myweb.loras.edu/Loras/PDF/AcademicCalendar2016-2017.pdf)


## The API

Because it has a free tier, we're using darksky.net.

```{r setKey}
darksky_api_key()
#""  Get your own key.

## Test

#get_current_forecast(42.5022,-90.692)
```

```{r pull2016}
 temp <- seq(mdy("8/24/2016"), mdy("9/16/2016"), by= 'days') %>%
  map(~get_forecast_for(42.5022,-90.692, .x)) 
  
temp %>% map_df("hourly") -> Weather2016
```


```{r investigate2016}
Weather2016 %>% gf_line(apparentTemperature ~ time)

```

```{r pull2017}

seq(mdy("8/23/2017"), mdy("9/15/2017"), by= 'days') %>%
  map(~get_forecast_for(42.5022,-90.692, .x)) %>% 
  map_df("hourly") -> 
  Weather2017

```


```{r pull2018}

seq(mdy("8/22/2018"), mdy("9/14/2018"), by= 'days') %>%
  map(~get_forecast_for(42.5022,-90.692, .x)) %>% 
  map_df("hourly") -> 
  Weather2018

```

```{r pull2019}

seq(mdy("8/21/2019"), mdy("9/13/2019"), by= 'days') %>%
  map(~get_forecast_for(42.5022,-90.692, .x)) %>% 
  map_df("hourly") -> 
  Weather2019

```


```{r writeOut}

save(Weather2016,Weather2017,Weather2018,Weather2019, file = "WeatherData.Rda")

```

```{r Begin cleaning}

Weather2016 %>% mutate(time=ymd_hms(time), HOUR = hour(time)) -> cleanWeather2016

Weather2017 %>% mutate(time=ymd_hms(time), HOUR = hour(time)) -> cleanWeather2017

Weather2018 %>% mutate(time=ymd_hms(time), HOUR = hour(time)) -> cleanWeather2018

Weather2019 %>% mutate(time=ymd_hms(time), HOUR = hour(time)) -> cleanWeather2019

```

```{r Create master weather set}
MasterWeather <- bind_rows(cleanWeather2016, cleanWeather2017, cleanWeather2018, cleanWeather2019)
```

```{r Run this to save}

save(cleanWeather2016, cleanWeather2017, cleanWeather2018, cleanWeather2019, file = "CleanWeatherData.rda")

```

